export enum AppState {
  IDLE = 'IDLE',
  CREATING = 'CREATING',
  WAITING = 'WAITING',
  CONNECTED = 'CONNECTED',
  SENDING = 'SENDING',
  RECEIVED = 'RECEIVED',
  INVALID_CODE = 'INVALID_CODE',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
  ROOM_EXPIRED = 'ROOM_EXPIRED'
}
